import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./pages/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: ["class", "body.dark"],
  theme: {
    extend: {
      //   colors: {
      //     // Raw colors from your theme
      //     alabaster: "#fafafa",
      //     antiFlashWhite: "#EBEBEB",
      //     black: "#000000",
      //     brightSun: "#FACF3D",
      //     burntSienna: "#ED6A5E",
      //     casablanca: "#F5BF4F",
      //     codGray: "#111010",
      //     doveGray: "#707070",
      //     eerieBlack: "#171717",
      //     manatee: "#8E8E90",
      //     mantis: "#62C554",
      //     mercury: "#E1E1E1",
      //     mineShaft: "#333333",
      //     outerSpace: "#373A3D",
      //     red: "red",
      //     royalBlue: "#2D6EEE",
      //     silver: "#C2C2C2",
      //     shark: "#202325",
      //     white: "#FFFFFF",

      //     // Semantic colors (using CSS variables for theme switching)
      //     bodyBg: "var(--body-bg)",
      //     bodyBgAccentOne: "var(--body-bg-accent-one)",
      //     text: "var(--text)",
      //     textSecondary: "var(--text-secondary)",
      //   },
      appDimensions: {
        appHorizontalGutters: "3%",
        appMaxWidth: "1400px",
        articleHeroImageMaxWidth: "1400px",
        articleMaxWidth: "600px",
        contactFormMaxWidth: "650px",
        footerDesktopHeight: "108px",
        footerTabletHeight: "164px",
        footerMobileHeight: "90px",
        modalMaxWidth: "600px",
        navbarDesktopHeight: "179px",
        navbarTabletHeight: "179px",
        navbarMobileHeight: "71px",
      },
      spacing: {
        nano: "2px",
        micro: "3px",
        xxSmall: "6px",
        xSmall: "8px",
        small: "10px",
        medium: "20px",
        large: "40px",
        xLarge: "50px",
        xxLarge: "70px",
        jumbo: "100px",
      },
      borderRadius: {
        nano: "2px",
        micro: "3px",
        small: "5px",
        medium: "8px",
        large: "15px",
        xLarge: "20px",
        xxLarge: "25px",
        jumbo: "35px",
        infinity: "9999px",
      },
      screens: {
        sm: "400px",
        md: "600px",
        lg: "1000px",
        xl: "1400px",
        "2xl": "1600px",
      },
      transitionDuration: {
        mini: "50ms",
        short: "100ms",
        medium: "300ms",
        long: "500ms",
      },
      maxWidth: {
        app: "1400px",
        article: "600px",
        contactForm: "650px",
      },
    },
  },
  plugins: [],
};

export default config;
