export type Book = {
  id: string;
  title: string;
  author: string;
  cover: string;
  url: string;
  height: number;
  width: number;
};

export const BOOKS: Book[] = [
  {
    id: "kitchen-confidential",
    title: "Kitchen Confidential",
    author: "Anthony Bourdain",
    cover: "/images/books/kitchen-confidential.webp", // TODO: Fix with .webp
    url: "https://a.co/d/0ayaogTn",
    height: 2400,
    width: 1617,
  },
  {
    id: "designing-data-intensive-applications",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann & Chris Riccomini",
    cover: "/images/books/designing-data-intensive-applications.jpg",
    url: "https://amzn.to/4bfEVg1",
    height: 394,
    width: 300,
  },
  {
    id: "the-power-broker",
    title: "The Power Broker",
    author: "Robert A. Caro",
    cover: "/images/books/the-power-broker.webp",
    url: "https://amzn.to/4lBeEwe",
    height: 1000,
    width: 655,
  },
  {
    id: "out-of-the-silent-planet",
    title: "Out of the Silent Planet",
    author: "C.S. Lewis",
    cover: "/images/books/out-of-the-silent-planet.webp",
    url: "https://amzn.to/3P2K1nd",
    height: 1000,
    width: 656,
  },
  {
    id: "perelandra",
    title: "Perelandra",
    author: "C.S. Lewis",
    cover: "/images/books/perelandra.webp",
    url: "https://amzn.to/4bdpAMZ",
    height: 1000,
    width: 656,
  },
  {
    id: "that-hideous-strength",
    title: "That Hideous Strength",
    author: "C.S. Lewis",
    cover: "/images/books/that-hideous-strength.webp",
    url: "https://amzn.to/4uxqmMb",
    height: 1000,
    width: 656,
  },
  // TODO: Move all these Chronicles of Narnia covers to modern versions
  {
    id: "the-magicians-nephew",
    title: "The Magician's Nephew",
    author: "C.S. Lewis",
    cover: "/images/books/the-magicians-nephew.webp",
    url: "https://amzn.to/3NJIZfn",
    height: 1015,
    width: 653,
  },
  {
    id: "the-lion-the-witch-and-the-wardrobe",
    title: "The Lion, the Witch, and the Wardrobe",
    author: "C.S. Lewis",
    cover: "/images/books/the-lion-the-witch-and-the-wardrobe.webp",
    url: "https://amzn.to/3NJIZfn",
    height: 1388,
    width: 924,
  },
  {
    id: "the-horse-and-his-boy",
    title: "The Horse and His Boy",
    author: "C.S. Lewis",
    cover: "/images/books/the-horse-and-his-boy.webp",
    url: "https://amzn.to/3NJIZfn",
    height: 2086,
    width: 1400,
  },
  {
    id: "prince-caspian",
    title: "Prince Caspian",
    author: "C.S. Lewis",
    cover: "/images/books/prince-caspian.jpg", // TODO: Fix with .webp
    url: "https://amzn.to/3NJIZfn",
    height: 2116,
    width: 1400,
  },
  {
    id: "the-voyage-of-the-dawn-treader",
    title: "The Voyage of the Dawn Treader",
    author: "C.S. Lewis",
    cover: "/images/books/the-voyage-of-the-dawn-treader.jpg", // TODO: Fix with .webp
    url: "https://amzn.to/3NJIZfn",
    height: 2117,
    width: 1400,
  },
  {
    id: "the-silver-chair",
    title: "The Silver Chair",
    author: "C.S. Lewis",
    cover: "/images/books/the-silver-chair.webp",
    url: "https://amzn.to/3NJIZfn",
    height: 2078,
    width: 1400,
  },
  {
    id: "the-last-battle",
    title: "The Last Battle",
    author: "C.S. Lewis",
    cover: "/images/books/the-last-battle.webp",
    url: "https://amzn.to/3NJIZfn",
    height: 2083,
    width: 1400,
  },
  {
    id: "when-money-dies",
    title: "When Money Dies",
    author: "Adam Fergusson",
    cover: "/images/books/when-money-dies.webp",
    url: "https://amzn.to/47A8TJb",
    height: 1000,
    width: 666,
  },
  {
    id: "barbarian-days",
    title: "Barbarian Days",
    author: "William Finnegan",
    cover: "/images/books/barbarian-days.webp",
    url: "https://amzn.to/4dngUos",
    height: 1000,
    width: 652,
  },
  {
    id: "mans-search-for-meaning",
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    cover: "/images/books/mans-search-for-meaning.webp",
    url: "https://amzn.to/3P92kXQ",
    height: 2048,
    width: 1272,
  },
  {
    id: "hackers-and-painters",
    title: "Hackers & Painters",
    author: "Paul Graham",
    cover: "/images/books/hackers-and-painters.webp",
    url: "https://amzn.to/4uvudJD",
    height: 1000,
    width: 646,
  },
  {
    id: "inside-delta-force",
    title: "Inside Delta Force",
    author: "Eric L. Haney",
    cover: "/images/books/inside-delta-force.webp",
    url: "https://amzn.to/4ly92CM",
    height: 1000,
    width: 713,
  },
  {
    id: "the-obstacle-is-the-way",
    title: "The Obstacle is the Way",
    author: "Ryan Holiday",
    cover: "/images/books/the-obstacle-is-the-way.webp",
    url: "https://amzn.to/4bwLc5X",
    height: 1000,
    width: 709,
  },
  {
    id: "the-psychology-of-money",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    cover: "/images/books/the-psychology-of-money.webp",
    url: "https://amzn.to/4bgUnHe",
    height: 1000,
    width: 647,
  },
  {
    id: "the-castle",
    title: "The Castle",
    author: "Franz Kafka",
    cover: "/images/books/the-castle.webp",
    url: "https://amzn.to/3Nj3QWO",
    height: 1000,
    width: 663,
  },
  {
    id: "shoe-dog",
    title: "Shoe Dog",
    author: "Phil Knight",
    cover: "/images/books/shoe-dog.webp",
    url: "https://amzn.to/4bzsgDE",
    height: 1000,
    width: 652,
  },
  {
    id: "the-art-of-racing-in-the-rain",
    title: "The Art of Racing in the Rain",
    author: "Garth Stein",
    cover: "/images/books/the-art-of-racing-in-the-rain.webp",
    url: "https://amzn.to/4sNT8Xk",
    height: 1000,
    width: 664,
  },
  {
    id: "the-hobbit",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    cover: "/images/books/the-hobbit.webp",
    url: "https://amzn.to/3PGr0XJ",
    height: 1000,
    width: 667,
  },
  {
    id: "the-fellowship-of-the-ring",
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    cover: "/images/books/the-fellowship-of-the-ring.webp",
    url: "https://amzn.to/4sd0CDd",
    height: 1000,
    width: 667,
  },
  {
    id: "the-two-towers",
    title: "The Two Towers",
    author: "J.R.R. Tolkien",
    cover: "/images/books/the-two-towers.webp",
    url: "https://amzn.to/4sd0CDd",
    height: 1000,
    width: 667,
  },
  {
    id: "the-return-of-the-king",
    title: "The Return of the King",
    author: "J.R.R. Tolkien",
    cover: "/images/books/the-return-of-the-king.webp",
    url: "https://amzn.to/4sd0CDd",
    height: 1000,
    width: 667,
  },
  {
    id: "steve-jobs",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    cover: "/images/books/steve-jobs.webp",
    url: "https://amzn.to/4rBOXge",
    height: 1869,
    width: 2846,
  },
  {
    id: "staff-engineer",
    title: "Staff Engineer",
    author: "Will Larson",
    cover: "/images/books/staff-engineer.webp",
    url: "https://amzn.to/414GS90",
    height: 1000,
    width: 627,
  },
].sort((a, b) => a.author.localeCompare(b.author));
