/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ViewsRouteImport } from './routes/views'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as CursorRouteImport } from './routes/cursor'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AtomRouteImport } from './routes/atom'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks/index'
import { Route as BookmarksAtomRouteImport } from './routes/bookmarks/atom'
import { Route as SlugOpengraphImageRouteImport } from './routes/$slug.opengraph-image'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsRoute = ViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const CursorRoute = CursorRouteImport.update({
  id: '/cursor',
  path: '/cursor',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomRoute = AtomRouteImport.update({
  id: '/atom',
  path: '/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksAtomRoute = BookmarksAtomRouteImport.update({
  id: '/bookmarks/atom',
  path: '/bookmarks/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugOpengraphImageRoute = SlugOpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => SlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/atom': typeof AtomRoute
  '/books': typeof BooksRoute
  '/cursor': typeof CursorRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/views': typeof ViewsRoute
  '/writing': typeof WritingRoute
  '/$slug/opengraph-image': typeof SlugOpengraphImageRoute
  '/bookmarks/atom': typeof BookmarksAtomRoute
  '/bookmarks/': typeof BookmarksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/atom': typeof AtomRoute
  '/books': typeof BooksRoute
  '/cursor': typeof CursorRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/views': typeof ViewsRoute
  '/writing': typeof WritingRoute
  '/$slug/opengraph-image': typeof SlugOpengraphImageRoute
  '/bookmarks/atom': typeof BookmarksAtomRoute
  '/bookmarks': typeof BookmarksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/atom': typeof AtomRoute
  '/books': typeof BooksRoute
  '/cursor': typeof CursorRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/views': typeof ViewsRoute
  '/writing': typeof WritingRoute
  '/$slug/opengraph-image': typeof SlugOpengraphImageRoute
  '/bookmarks/atom': typeof BookmarksAtomRoute
  '/bookmarks/': typeof BookmarksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/atom'
    | '/books'
    | '/cursor'
    | '/opengraph-image'
    | '/views'
    | '/writing'
    | '/$slug/opengraph-image'
    | '/bookmarks/atom'
    | '/bookmarks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/atom'
    | '/books'
    | '/cursor'
    | '/opengraph-image'
    | '/views'
    | '/writing'
    | '/$slug/opengraph-image'
    | '/bookmarks/atom'
    | '/bookmarks'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/atom'
    | '/books'
    | '/cursor'
    | '/opengraph-image'
    | '/views'
    | '/writing'
    | '/$slug/opengraph-image'
    | '/bookmarks/atom'
    | '/bookmarks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AtomRoute: typeof AtomRoute
  BooksRoute: typeof BooksRoute
  CursorRoute: typeof CursorRoute
  OpengraphImageRoute: typeof OpengraphImageRoute
  ViewsRoute: typeof ViewsRoute
  WritingRoute: typeof WritingRoute
  BookmarksAtomRoute: typeof BookmarksAtomRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursor': {
      id: '/cursor'
      path: '/cursor'
      fullPath: '/cursor'
      preLoaderRoute: typeof CursorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom': {
      id: '/atom'
      path: '/atom'
      fullPath: '/atom'
      preLoaderRoute: typeof AtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/atom': {
      id: '/bookmarks/atom'
      path: '/bookmarks/atom'
      fullPath: '/bookmarks/atom'
      preLoaderRoute: typeof BookmarksAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/opengraph-image': {
      id: '/$slug/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/$slug/opengraph-image'
      preLoaderRoute: typeof SlugOpengraphImageRouteImport
      parentRoute: typeof SlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugOpengraphImageRoute: typeof SlugOpengraphImageRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugOpengraphImageRoute: SlugOpengraphImageRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AtomRoute: AtomRoute,
  BooksRoute: BooksRoute,
  CursorRoute: CursorRoute,
  OpengraphImageRoute: OpengraphImageRoute,
  ViewsRoute: ViewsRoute,
  WritingRoute: WritingRoute,
  BookmarksAtomRoute: BookmarksAtomRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
